Feature/admin routes
Yunya-Hsu/twitter-fullstack-2020 pull request #5
Opened 2022-07-27 03:46 UTC by Yunya-Hsu

**Overall**
1. 新增 handlebars helpers，並於 app.js 中引用
2. handlebars helpers 共兩個功能：(1) 使用 dayjs 將固定時間調整為相對時間，且以中文顯示、(2) 在 .hbs 檔案中增加判斷 if (a === b) 的功能
3. 增加 user-avatar 和 user-cover 的範例圖片

**Admin**
1. Admin 可以瀏覽全站的 Tweet 清單，此清單以「建立日期」排序，越新的貼文在月前面。
2. 全站 Tweet 清單上，每則 Tweet 僅快覽該則貼文的前 50 個字
3. Admin 可以在清單上直接刪除任何人的推文
4. 當 Admin 刪除推文後，與該則貼文相關的reply & like 也會被刪除
5. Admin 可以瀏覽站內所有的使用者清單，清單資訊包含：推文數量（所發表的 Tweet 累積總量）、關注人數、跟隨者人數、推文被 like 的數量（所發表的 Tweet 獲得 like 的「累積」總量）
6. 增加 admin-nav-left 的 partial 
7. 增加 admin/users 和 admin/tweets 的頁面

2022-07-27 08:06 UTC, ks0dcongra requested changes
前端方面須在微調!

2022-07-28 05:22 UTC, ks0dcongra commented
一test

2022-07-28 05:23 UTC, ks0dcongra approved these changes
ok go to merge!

2022-07-28 06:57 UTC, Yunya-Hsu commented
re-open, to merge this PR

2022-07-28 06:58 UTC, Yunya-Hsu commented
re-open, to merge this PR

2022-07-28 07:03 UTC, merged